from pathlib import Path


def read(path):
    return Path(path).read_text(encoding="utf-8").replace("\r\n", "\n")


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def rep(path, old, new, count=1):
    text = read(path)
    if old not in text:
        raise SystemExit(f"Expected source block not found in {path}: {old[:120]!r}")
    text = text.replace(old, new, count)
    write(path, text)


write("apps/CYERPAutoInput/BUILD", "20\n")
rep("apps/CYERPAutoInput/AppLogger.cs", "CYERPAutoInput V0.1.0 Build 19 starting", "CYERPAutoInput V0.1.0 Build 20 starting")
rep("apps/CYERPAutoInput/Build10UiPatch.cs", "V0.1.0 Build 19 · Esc：緊急停止 · 不自動儲存 ERP", "V0.1.0 Build 20 · Esc：緊急停止 · 不自動儲存 ERP")
rep("apps/CYERPAutoInput/MainForm.cs", "V0.1.0 Build 9 · Esc：緊急停止 · 不自動儲存 ERP", "V0.1.0 Build 20 · Esc：緊急停止 · 不自動儲存 ERP")

rep(
    "apps/CYERPAutoInput/MainForm.cs",
    '        _details.Columns.Add(TextColumn("Batch", "批號", 170));\n',
    '        var batchColumn = TextColumn("Batch", "批號（自動）", 170);\n        batchColumn.ReadOnly = true;\n        _details.Columns.Add(batchColumn);\n',
)

rep(
    "apps/CYERPAutoInput/MainForm.cs",
    "            await _automation.RunAsync(snapshot, progress, token);\n",
    "            var result = await _automation.RunAsync(snapshot, progress, token);\n            var salesNo = string.IsNullOrWhiteSpace(result.SalesOrderNumber) ? \"未取得\" : result.SalesOrderNumber;\n            if (result.Warnings.Count > 0)\n                SetStatus($\"ERP：銷貨單 {salesNo} 輸入完成；{result.Warnings.Count} 筆需人工確認；尚未儲存\");\n            else\n                SetStatus($\"ERP：銷貨單 {salesNo} 輸入完成；尚未儲存\");\n",
)

rep(
    "apps/CYERPAutoInput/OcrTextNormalizer.cs",
    "        ['总'] = '總', ['统'] = '統', ['应'] = '應', ['计'] = '計'\n",
    "        ['总'] = '總', ['统'] = '統', ['应'] = '應', ['计'] = '計', ['现'] = '現'\n",
)

rep(
    "apps/CYERPAutoInput/NativeMethods.cs",
    "    internal const uint WM_SETTEXT = 0x000C;\n    internal const uint EM_SETSEL = 0x00B1;\n",
    "    internal const uint WM_SETTEXT = 0x000C;\n    internal const uint WM_COPY = 0x0301;\n    internal const uint EM_SETSEL = 0x00B1;\n",
)

resolver_insert = """
    public static WindowControl ResolveSalesOrderNumber(nint root)
    {
        if (!NativeMethods.GetWindowRect(root, out var rr))
            throw new InvalidOperationException("ERP root rectangle unavailable.");
        var candidates = Win32Automation.EnumerateChildren(root)
            .Where(c => c.Visible && c.ClassName.Equals("TDBEdit", StringComparison.OrdinalIgnoreCase))
            .Where(c => c.Rect.Top - rr.Top is >= 140 and <= 245)
            .ToList();
        var rows = BuildRows(candidates, 9);
        if (rows.Count != 2 || rows.Any(r => r.Count != 3))
            throw new InvalidOperationException($"ERP 表頭結構不符預期 [3,3]，實際 rows={rows.Count}。");

        // COPI08 first row is 銷貨單別 / 銷貨單號 / 單據日期. The middle
        // TDBEdit is generated by ERP after the type/date are accepted; CY never
        // writes to it and only reads it for batch-run traceability.
        return rows[0][1];
    }

"""
rep(
    "apps/CYERPAutoInput/ErpLayoutResolver.cs",
    "    public static WindowControl ResolveTabField(nint sheet, string group, string key)\n",
    resolver_insert + "    public static WindowControl ResolveTabField(nint sheet, string group, string key)\n",
)

peers_insert = """
    public static IReadOnlyList<nint> FindVisibleProcessPeerWindows(nint root)
    {
        if (root == 0) return Array.Empty<nint>();
        NativeMethods.GetWindowThreadProcessId(root, out var processId);
        if (processId == 0) return Array.Empty<nint>();

        var peers = new List<nint>();
        NativeMethods.EnumWindows((hwnd, _) =>
        {
            if (hwnd == root || !NativeMethods.IsWindowVisible(hwnd)) return true;
            NativeMethods.GetWindowThreadProcessId(hwnd, out var pid);
            if (pid != processId) return true;
            if (!NativeMethods.GetWindowRect(hwnd, out var rect)) return true;
            if (rect.Width is < 140 or > 1200 || rect.Height is < 70 or > 800) return true;
            peers.Add(hwnd);
            return true;
        }, 0);
        return peers;
    }

    public static bool WindowTreeContainsText(nint hwnd, string expectedText)
    {
        var target = OcrTextNormalizer.Normalize(expectedText);
        if (target.Length == 0 || hwnd == 0) return false;
        if (OcrTextNormalizer.Normalize(NativeMethods.WindowText(hwnd)).Contains(target, StringComparison.Ordinal))
            return true;

        return EnumerateChildren(hwnd)
            .Where(c => c.Visible)
            .Select(c => OcrTextNormalizer.Normalize(c.Text))
            .Any(text => text.Contains(target, StringComparison.Ordinal));
    }

"""
rep(
    "apps/CYERPAutoInput/Win32Automation.cs",
    "    public static string NormalizeLabel(string value)\n",
    peers_insert + "    public static string NormalizeLabel(string value)\n",
)

write(
    "apps/CYERPAutoInput/AutomationRunResult.cs",
    """namespace CYERPAutoInput;

internal sealed class AutomationRunResult
{
    public string SalesOrderNumber { get; set; } = string.Empty;
    public List<AutomationWarning> Warnings { get; } = [];
}

internal sealed record AutomationWarning(
    string Code,
    string SalesOrderNumber,
    int DetailRow,
    string ItemCode,
    string Message);
""",
)

write(
    "apps/CYERPAutoInput/F2BatchCellLocator.cs",
    """using System.Drawing.Imaging;
using System.Globalization;

namespace CYERPAutoInput;

internal sealed record BatchStockSelection(Point Point, int RowNumber, decimal Stock);

internal sealed class F2BatchCellLocator
{
    private readonly WindowsOcrService _ocr;
    private readonly AppLogger _log;

    public F2BatchCellLocator(WindowsOcrService ocr, AppLogger log)
    {
        _ocr = ocr;
        _log = log;
    }

    public async Task<BatchStockSelection> FindFirstPositiveStockAsync(
        nint lookupHwnd,
        CancellationToken cancellationToken)
    {
        var grid = Win32Automation.EnumerateChildren(lookupHwnd)
            .Where(c => c.Visible && c.ClassName.Equals("TcxGridSite", StringComparison.OrdinalIgnoreCase))
            .Where(c => c.Rect.Width >= 180 && c.Rect.Height >= 70)
            .OrderByDescending(c => c.Rect.Width * c.Rect.Height)
            .FirstOrDefault();
        if (grid is null)
            throw new InvalidOperationException("F2 批號查詢找不到可用的 TcxGridSite；已停止目前單據。");

        var captureRect = grid.Rect.ToRectangle();
        using var image = ScreenCapture.Capture(captureRect);
        var tokens = await _ocr.RecognizeAsync(image, cancellationToken, requireChinese: true);
        var header = FastDetailGridVisionService.FindExactPhrase(tokens, ["現有存量"]);
        if (header is null)
            throw new InvalidOperationException("F2 批號查詢無法可靠辨識「現有存量」欄；已停止目前單據。");

        var rawVertical = GridVisionService.FindVerticalLines(image, Math.Min(image.Height - 1, 120));
        var boundaries = NormalizeBoundaries(rawVertical, image.Width);
        var headerCenterX = header.Value.Left + header.Value.Width / 2;
        var interval = FindInterval(boundaries, headerCenterX);
        if (interval < 0 || interval + 1 >= boundaries.Count)
            throw new InvalidOperationException("F2 批號查詢無法由即時格線定位「現有存量」欄；已停止目前單據。");

        var left = boundaries[interval];
        var right = boundaries[interval + 1];
        if (right - left < 24)
            throw new InvalidOperationException("F2 批號查詢的「現有存量」欄寬異常；已停止目前單據。");

        var horizontal = GridVisionService.FindHorizontalLines(image, Math.Max(0, header.Value.Bottom - 5));
        var first = horizontal.FindIndex(y => y >= header.Value.Bottom - 3);
        if (first < 0 || horizontal.Count - first < 2)
            throw new InvalidOperationException("F2 批號查詢無法辨識資料列；已停止目前單據。");

        var rowNumber = 0;
        for (var i = first; i + 1 < horizontal.Count; i++)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var top = horizontal[i];
            var bottom = horizontal[i + 1];
            var height = bottom - top;
            if (height < 14 || height > 64) continue;
            rowNumber++;

            var crop = Rectangle.FromLTRB(
                Math.Clamp(left + 2, 0, image.Width - 1),
                Math.Clamp(top + 1, 0, image.Height - 1),
                Math.Clamp(right - 2, 1, image.Width),
                Math.Clamp(bottom - 1, 1, image.Height));
            if (crop.Width < 8 || crop.Height < 8) continue;

            using var cell = image.Clone(crop, PixelFormat.Format32bppArgb);
            using var enhanced = EnhanceCell(cell, 3);
            var cellTokens = await _ocr.RecognizeAsync(enhanced, cancellationToken);
            var rawText = string.Concat(cellTokens
                .OrderBy(t => t.Rect.Top)
                .ThenBy(t => t.Rect.Left)
                .Select(t => t.Text));

            if (!TryParseStockText(rawText, out var stock))
            {
                _log.Info("vision", $"F2 batch stock row={rowNumber} parse=false chars={rawText.Trim().Length}");
                continue;
            }

            _log.Info("vision", $"F2 batch stock row={rowNumber} stock={stock.ToString(CultureInfo.InvariantCulture)}");
            if (stock <= 0) continue;

            var point = new Point(
                captureRect.Left + (left + right) / 2,
                captureRect.Top + (top + bottom) / 2);
            _log.Info("vision", $"F2 batch first positive stock selected row={rowNumber} point={point.X},{point.Y} stock={stock.ToString(CultureInfo.InvariantCulture)}");
            return new BatchStockSelection(point, rowNumber, stock);
        }

        throw new InvalidOperationException("F2 批號查詢沒有找到「現有存量 > 0」的批號；已停止目前單據。");
    }

    internal static bool TryParseStockText(string raw, out decimal value)
    {
        value = 0;
        var text = raw.Trim()
            .Replace(" ", string.Empty)
            .Replace("　", string.Empty)
            .Replace(",", string.Empty)
            .Replace("，", string.Empty);
        if (text.Length == 0) return false;

        const NumberStyles styles = NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint;
        return decimal.TryParse(text, styles, CultureInfo.InvariantCulture, out value) ||
               decimal.TryParse(text, NumberStyles.Number, CultureInfo.CurrentCulture, out value);
    }

    private static int FindInterval(IReadOnlyList<int> boundaries, int x)
    {
        for (var i = 0; i + 1 < boundaries.Count; i++)
            if (x >= boundaries[i] && x <= boundaries[i + 1]) return i;
        return -1;
    }

    private static List<int> NormalizeBoundaries(IReadOnlyList<int> rawLines, int width)
    {
        var boundaries = rawLines.Where(x => x >= 0 && x < width).Distinct().OrderBy(x => x).ToList();
        if (boundaries.Count == 0 || boundaries[0] > 5) boundaries.Insert(0, 0);
        if (boundaries[^1] < width - 5) boundaries.Add(width - 1);

        var changed = true;
        while (changed && boundaries.Count > 2)
        {
            changed = false;
            for (var i = 0; i + 1 < boundaries.Count; i++)
            {
                if (boundaries[i + 1] - boundaries[i] >= 18) continue;
                if (i == 0) boundaries.RemoveAt(i + 1);
                else boundaries.RemoveAt(i);
                changed = true;
                break;
            }
        }
        return boundaries;
    }

    private static Bitmap EnhanceCell(Bitmap source, int scale)
    {
        var width = Math.Max(1, source.Width * scale);
        var height = Math.Max(1, source.Height * scale);
        var output = new Bitmap(width, height, PixelFormat.Format32bppArgb);

        var total = 0L;
        var samples = 0;
        for (var y = 0; y < source.Height; y += 2)
        for (var x = 0; x < source.Width; x += 2)
        {
            var c = source.GetPixel(x, y);
            total += (c.R * 30 + c.G * 59 + c.B * 11) / 100;
            samples++;
        }
        var average = samples == 0 ? 255 : (int)(total / samples);
        var invert = average < 145;

        for (var y = 0; y < height; y++)
        {
            var sy = Math.Min(source.Height - 1, y / scale);
            for (var x = 0; x < width; x++)
            {
                var sx = Math.Min(source.Width - 1, x / scale);
                var c = source.GetPixel(sx, sy);
                var luma = (c.R * 30 + c.G * 59 + c.B * 11) / 100;
                if (invert) luma = 255 - luma;
                var contrasted = (int)Math.Round((luma - 128) * 1.35 + 128);
                var v = Math.Clamp(contrasted, 0, 255);
                output.SetPixel(x, y, Color.FromArgb(255, v, v, v));
            }
        }
        return output;
    }
}
""",
)

rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "    private readonly F2UnitCellLocator _unitCellLocator;\n",
    "    private readonly F2UnitCellLocator _unitCellLocator;\n    private readonly F2BatchCellLocator _batchCellLocator;\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "        _unitCellLocator = new F2UnitCellLocator(ocr, log);\n        _ = Task.Run(() => WarmUpOcrAsync(ocr));\n",
    "        _unitCellLocator = new F2UnitCellLocator(ocr, log);\n        _batchCellLocator = new F2BatchCellLocator(ocr, log);\n        _ = Task.Run(() => WarmUpOcrAsync(ocr));\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "    public async Task RunAsync(FormSnapshot snapshot, IProgress<string> progress, CancellationToken cancellationToken)\n    {\n        var root = FindErp();\n",
    "    public async Task<AutomationRunResult> RunAsync(FormSnapshot snapshot, IProgress<string> progress, CancellationToken cancellationToken)\n    {\n        var result = new AutomationRunResult();\n        var root = FindErp();\n",
)
rep("apps/CYERPAutoInput/ErpAutomationService.cs", "        await FillHeaderAsync(root, snapshot, cancellationToken);\n", "        await FillHeaderAsync(root, snapshot, result, cancellationToken);\n")
rep("apps/CYERPAutoInput/ErpAutomationService.cs", "            await FillDetailsAsync(root, snapshot.Details, progress, cancellationToken);\n", "            await FillDetailsAsync(root, snapshot.Details, result, progress, cancellationToken);\n")
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "        progress.Report(\"ERP：輸入完成；依目前安全規則未自動儲存。\");\n        _log.Info(\"automation\", \"input completed; ERP save intentionally not invoked\");\n    }\n",
    "        progress.Report(\"ERP：輸入完成；依目前安全規則未自動儲存。\");\n        _log.Info(\"automation\", $\"input completed sales_no={result.SalesOrderNumber} warnings={result.Warnings.Count}; ERP save intentionally not invoked\");\n        return result;\n    }\n",
)

rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "    private async Task FillHeaderAsync(nint root, FormSnapshot snapshot, CancellationToken cancellationToken)\n    {\n",
    "    private async Task FillHeaderAsync(nint root, FormSnapshot snapshot, AutomationRunResult result, CancellationToken cancellationToken)\n    {\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "            await SetFieldAsync(root, target, field, value, cancellationToken);\n            _log.Info(\"field\", $\"filled group={field.Group} key={field.Key} chars={value.Length}\");\n        }\n    }\n\n    private async Task FillTabGroupAsync",
    "            await SetFieldAsync(root, target, field, value, cancellationToken);\n            _log.Info(\"field\", $\"filled group={field.Group} key={field.Key} chars={value.Length}\");\n            if (field.Key == \"order_date\" && string.IsNullOrWhiteSpace(result.SalesOrderNumber))\n                result.SalesOrderNumber = await CaptureSalesOrderNumberAsync(root, cancellationToken);\n        }\n\n        if (string.IsNullOrWhiteSpace(result.SalesOrderNumber))\n            result.SalesOrderNumber = await CaptureSalesOrderNumberAsync(root, cancellationToken);\n    }\n\n    private async Task<string> CaptureSalesOrderNumberAsync(nint root, CancellationToken cancellationToken)\n    {\n        var target = ErpLayoutResolver.ResolveSalesOrderNumber(root);\n        if (!Win32Automation.PrepareForeground(root, _log))\n            throw new InvalidOperationException(\"讀取銷貨單號前無法把 COPI08 帶到前景。\");\n\n        var center = new Point((target.Rect.Left + target.Rect.Right) / 2, (target.Rect.Top + target.Rect.Bottom) / 2);\n        InputSender.Click(center);\n        await Delay(80, cancellationToken);\n\n        var direct = NativeMethods.WindowText(target.Handle).Trim();\n        var beforeClipboard = string.Empty;\n        try\n        {\n            if (Clipboard.ContainsText()) beforeClipboard = Clipboard.GetText().Trim();\n            NativeMethods.SendMessage(target.Handle, NativeMethods.EM_SETSEL, nint.Zero, new nint(-1));\n            NativeMethods.SendMessage(target.Handle, NativeMethods.WM_COPY, nint.Zero, nint.Zero);\n            await Delay(80, cancellationToken);\n        }\n        catch (Exception ex)\n        {\n            _log.Warn(\"document\", $\"sales order clipboard copy raised {ex.GetType().Name}; exact Win32 text fallback will be evaluated\");\n        }\n\n        var copied = string.Empty;\n        try\n        {\n            if (Clipboard.ContainsText()) copied = Clipboard.GetText().Trim();\n        }\n        catch { }\n\n        string value;\n        string source;\n        if (IsPlausibleSalesOrderNumber(copied) &&\n            (direct.Length == 0 ? copied != beforeClipboard || beforeClipboard.Length == 0 : copied == direct))\n        {\n            value = copied;\n            source = \"clipboard\";\n        }\n        else if (IsPlausibleSalesOrderNumber(direct))\n        {\n            value = direct;\n            source = \"win32-text\";\n        }\n        else\n        {\n            throw new InvalidOperationException(\"ERP 已輸入銷貨單別／日期，但無法精確取得 ERP 自動產生的銷貨單號；為避免批次追蹤錯單已停止。\");\n        }\n\n        _log.Info(\"document\", $\"sales order number captured sales_no={value} source={source}\");\n        return value;\n    }\n\n    private static bool IsPlausibleSalesOrderNumber(string value)\n    {\n        if (string.IsNullOrWhiteSpace(value) || value.Length is < 4 or > 32) return false;\n        if (value.Any(char.IsWhiteSpace) || value.Contains('*')) return false;\n        return value.Count(char.IsLetterOrDigit) >= 4;\n    }\n\n    private async Task FillTabGroupAsync",
)

rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "    private async Task FillDetailsAsync(nint root, IReadOnlyList<DetailRow> rows, IProgress<string> progress, CancellationToken cancellationToken)\n",
    "    private async Task FillDetailsAsync(nint root, IReadOnlyList<DetailRow> rows, AutomationRunResult result, IProgress<string> progress, CancellationToken cancellationToken)\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "                InputSender.Press(NativeMethods.VK_DOWN);\n                await Delay(320, cancellationToken);\n                _log.Info(\"detail\", $\"next row activated by Down logical_row={rowIndex + 1}\");\n",
    "                InputSender.Press(NativeMethods.VK_DOWN);\n                await Delay(180, cancellationToken);\n                await HandleRowTransitionDialogsAsync(root, result, rowIndex, rows[rowIndex - 1], cancellationToken);\n                await Delay(140, cancellationToken);\n                _log.Info(\"detail\", $\"next row activated by Down logical_row={rowIndex + 1}\");\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "            geometry = await SetDetailCellAsync(root, grid, geometry, visibleRow, 0, row.ItemCode, cancellationToken);\n\n            if (!string.IsNullOrWhiteSpace(row.Unit))\n",
    "            geometry = await SetDetailCellAsync(root, grid, geometry, visibleRow, 0, row.ItemCode, cancellationToken);\n            geometry = await SelectBatchIfRequiredAsync(root, grid, geometry, visibleRow, row.ItemCode, cancellationToken);\n\n            if (!string.IsNullOrWhiteSpace(row.Unit))\n",
)
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "            if (!string.IsNullOrWhiteSpace(row.UnitPrice))\n                geometry = await SetDetailCellAsync(root, grid, geometry, visibleRow, 7, row.UnitPrice, cancellationToken);\n            if (!string.IsNullOrWhiteSpace(row.Batch))\n                _log.Info(\"detail\", $\"batch requested row={rowIndex + 1}; batch automation remains deferred\");\n",
    "            if (!string.IsNullOrWhiteSpace(row.UnitPrice))\n                geometry = await SetDetailCellAsync(root, grid, geometry, visibleRow, 7, row.UnitPrice, cancellationToken);\n",
)

new_methods = """
    private async Task<GridGeometry> SelectBatchIfRequiredAsync(
        nint root,
        WindowControl grid,
        GridGeometry geometry,
        int visibleRow,
        string itemCode,
        CancellationToken cancellationToken)
    {
        geometry = await EnsureDetailColumnVisibleAsync(root, grid, geometry, visibleRow, 5, cancellationToken);
        if (!Win32Automation.PrepareForeground(root, _log))
            throw new InvalidOperationException("檢查批號欄前無法把 ERP 帶到前景。");

        var (activeGeometry, point, freshRect) = await ResolveFreshDetailCellPointAsync(grid.Handle, geometry, visibleRow, 5, cancellationToken);
        geometry = activeGeometry;
        InputSender.Click(point);
        await Delay(120, cancellationToken);

        var editor = await WaitGridEditorAsync(root, freshRect, point, cancellationToken, 220);
        if (editor == 0)
        {
            InputSender.Press(NativeMethods.VK_RETURN);
            editor = await WaitGridEditorAsync(root, freshRect, point, cancellationToken, 720);
        }
        if (editor == 0)
            throw new InvalidOperationException($"品號 {itemCode}：無法可靠進入批號欄；為避免後續欄位錯位已停止。");

        var marker = NativeMethods.WindowText(editor).Trim();
        var starCount = marker.Count(ch => ch == '*');
        _log.Info("detail", $"batch probe row={visibleRow + 1} item={itemCode} marker_chars={marker.Length} stars={starCount}");

        if (marker.Length == 0)
        {
            _log.Info("detail", $"batch not required row={visibleRow + 1} item={itemCode}");
            return geometry;
        }

        if (starCount == 0)
        {
            _log.Info("detail", $"batch already populated/non-marker row={visibleRow + 1} item={itemCode} chars={marker.Length}");
            return geometry;
        }

        InputSender.Press(NativeMethods.VK_F2);
        var lookup = await WaitLookupAsync(cancellationToken);
        if (lookup == 0)
            throw new InvalidOperationException($"品號 {itemCode} 需要批號，但按 F2 後沒有出現批號查詢視窗。");
        if (!Win32Automation.PrepareForeground(lookup, _log))
            throw new InvalidOperationException("F2 批號查詢視窗無法取得前景。");
        await Delay(120, cancellationToken);

        var selection = await _batchCellLocator.FindFirstPositiveStockAsync(lookup, cancellationToken);
        InputSender.Click(selection.Point);
        await Delay(120, cancellationToken);

        var focus = NativeMethods.FocusedControlOfForeground(lookup);
        if (focus == 0 || !NativeMethods.ClassName(focus).Equals("TcxGridSite", StringComparison.OrdinalIgnoreCase))
        {
            _log.Warn("detail", $"F2 batch row click did not focus grid first_try class={NativeMethods.ClassName(focus)}");
            InputSender.Click(selection.Point);
            await Delay(120, cancellationToken);
            focus = NativeMethods.FocusedControlOfForeground(lookup);
        }
        if (focus == 0 || !NativeMethods.ClassName(focus).Equals("TcxGridSite", StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("已點到正庫存批號列，但 F2 表格沒有取得可驗證焦點；為避免 Enter 送到錯誤控制項已停止。");

        InputSender.Press(NativeMethods.VK_RETURN);
        if (!await WaitWindowClosedAsync(lookup, 1400, cancellationToken))
            throw new InvalidOperationException("已選取正庫存批號並送出 Enter，但 F2 視窗仍未關閉。");

        if (!Win32Automation.PrepareForeground(root, _log))
            throw new InvalidOperationException("批號 F2 關閉後無法回到 ERP 前景。");
        await Delay(120, cancellationToken);
        _log.Info("detail", $"batch selected row={visibleRow + 1} item={itemCode} lookup_row={selection.RowNumber} positive_stock={selection.Stock}");
        return geometry;
    }

    private async Task HandleRowTransitionDialogsAsync(
        nint root,
        AutomationRunResult result,
        int completedDetailRow,
        DetailRow completedRow,
        CancellationToken cancellationToken)
    {
        var peers = Win32Automation.FindVisibleProcessPeerWindows(root);
        if (peers.Count == 0) return;

        const string knownWarning = "庫存量或批號量不足";
        foreach (var peer in peers)
        {
            cancellationToken.ThrowIfCancellationRequested();
            var known = Win32Automation.WindowTreeContainsText(peer, knownWarning);
            if (!known)
                known = await _textVision.FindTextAsync(peer, [knownWarning], cancellationToken) is not null;
            if (!known) continue;

            if (!Win32Automation.PrepareForeground(peer, _log))
                throw new InvalidOperationException("ERP 批號存量不足警告已出現，但無法安全取得警告視窗焦點。");
            InputSender.Press(NativeMethods.VK_RETURN);
            if (!await WaitWindowClosedAsync(peer, 1200, cancellationToken))
                throw new InvalidOperationException("已對批號存量不足警告送出 Enter，但警告視窗沒有關閉；已停止避免後續錯位。");

            var warning = new AutomationWarning(
                "BATCH_STOCK_INSUFFICIENT",
                result.SalesOrderNumber,
                completedDetailRow,
                completedRow.ItemCode,
                "批號存量不足，需人工確認");
            result.Warnings.Add(warning);
            _log.Warn("document", $"warning recorded code={warning.Code} sales_no={warning.SalesOrderNumber} detail_row={warning.DetailRow} item={warning.ItemCode}");

            if (!Win32Automation.PrepareForeground(root, _log))
                throw new InvalidOperationException("關閉批號存量不足警告後無法回到 COPI08；已停止避免後續錯位。");
            return;
        }

        throw new InvalidOperationException("切換商品明細下一列時 ERP 出現未預期視窗；為避免資料填入錯誤欄位已立即停止目前單據。");
    }

"""
rep(
    "apps/CYERPAutoInput/ErpAutomationService.cs",
    "    private async Task<GridGeometry> EnsureDetailColumnVisibleAsync(\n",
    new_methods + "    private async Task<GridGeometry> EnsureDetailColumnVisibleAsync(\n",
)

selftest_insert = """
            if (!F2BatchCellLocator.TryParseStockText("67", out var batchStock67) || batchStock67 != 67 ||
                !F2BatchCellLocator.TryParseStockText("100.0000", out var batchStock100) || batchStock100 != 100 ||
                !F2BatchCellLocator.TryParseStockText("1,234", out var batchStock1234) || batchStock1234 != 1234 ||
                F2BatchCellLocator.TryParseStockText("批號", out _))
                throw new InvalidOperationException("F2 batch stock parser regression failed.");

            if (OcrTextNormalizer.Normalize("现有存量") != "現有存量")
                throw new InvalidOperationException("Batch-stock Traditional/Simplified OCR normalization failed.");

"""
rep(
    "apps/CYERPAutoInput/VisionSelfTest.cs",
    "            var ocr = new WindowsOcrService(log);\n",
    selftest_insert + "            var ocr = new WindowsOcrService(log);\n",
)

readme_path = "apps/CYERPAutoInput/README.md"
readme = read(readme_path)
readme = readme.replace(
    "-> 品號 -> 單位(F2) -> 數量 -> 其他明細；每格以 Enter 完成",
    "-> 品號 -> ERP自動判斷批號(F2選第一筆正庫存) -> 單位(F2) -> 數量 -> 其他明細；每格以 Enter 完成",
)
readme = readme.replace(
    "- F2 單位：先定位 `TcxGridSite` 與「換算單位」欄；必要時逐格裁切後用 PP-OCRv5 辨識「支／箱」等短字，再點選該格並送一次 Enter。",
    "- F2 單位：先定位 `TcxGridSite` 與「換算單位」欄；必要時逐格裁切後用 PP-OCRv5 辨識「支／箱」等短字，再點選該格並送一次 Enter。\n- F2 批號：品號輸入後檢查批號欄；若 ERP 顯示 `************`，開啟批號 F2，辨識「現有存量」欄並選取由上往下第一筆 `> 0` 的批號。批號數量不足警告屬可記錄警告，確認後以 Enter 通過。",
)
readme = readme.replace(
    "  docs/\n    README.md\n    THIRD_PARTY_NOTICES.md\n",
    "  README.md\n  THIRD_PARTY_NOTICES.md\n",
)
readme = readme.replace(
    "- 不自行輸入銷貨單號。",
    "- 不自行輸入銷貨單號；ERP 在銷貨單別／日期完成後自動產生，CY 只精確讀取以供批次追蹤。\n- 任何未預期視窗／焦點／欄位狀態都必須停止目前單據，禁止猜座標繼續輸入。",
)
if "## TODO" not in readme:
    readme += """
## TODO

- **跨批號自動分配 / 拆列**：例如銷售 100、批號庫存 67 + 100 時，自動拆成 67 + 33。實作前必須先定義批號優先順序、效期、總庫存不足與來源訂單對應規則。
- **批次 Fault Isolation / Recovery**：未來 XLS/XLSX 多單批次輸入時，單張發生 hard failure 要記錄來源訂單、ERP 銷貨單號、失敗階段與原因，安全跳過該張後繼續；若無法驗證 ERP 已回復安全起始狀態則停止整批。
- **批次結果總表**：中途可安全處理的 warning 不逐張跳 MessageBox；全部完成後統一列出成功、需人工確認、失敗的訂單與銷貨單號。
- **自動儲存**：待單張輸入、批號與 recovery gate 穩定後，再加入每張單的 ERP 儲存與下一張流程。
"""
write(readme_path, readme)
