<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>CYInvoice.Sync.Tests</RootNamespace>
    <AssemblyName>CYInvoice.Sync.Tests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/CYInvoice.Core/CYInvoice.Core.csproj" />
  </ItemGroup>
</Project>
