//go:build windows

package main

import (
	"fmt"
	"strconv"
	"syscall"
	"unsafe"
)

func textExtent(hdc, font uintptr, text string) SIZE {
	if text == "" { return SIZE{} }
	old, _, _ := procSelectObject.Call(hdc, font); defer procSelectObject.Call(hdc, old)
	units := syscall.StringToUTF16(text); if len(units)==0{return SIZE{}}
	var sz SIZE
	procGetTextExtentPoint32W.Call(hdc, uintptr(unsafe.Pointer(&units[0])), uintptr(len(units)-1), uintptr(unsafe.Pointer(&sz)))
	return sz
}

func upperMoneyDigit(d int64) string { digits:=[]string{"零","壹","貳","參","肆","伍","陸","柒","捌","玖"};if d<0||d>9{return "零"};return digits[d] }

func drawFixedChineseTotal(hdc uintptr, label string, cents int64, hasData bool, r RECT, strikePen uintptr) {
	x:=r.Left; labelSize:=textExtent(hdc,fontInvoiceAmountUnit,label); drawText(hdc,label,RECT{x,r.Top,x+labelSize.Cx+4,r.Bottom},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceAmountUnit,rgb(45,86,89));x+=labelSize.Cx+14
	units:=[]string{"億","仟","佰","拾","萬","仟","佰","拾","元"};divisors:=[]int64{100000000,10000000,1000000,100000,10000,1000,100,10,1};available:=r.Right-x;if available<=0{return};slotW:=available/int32(len(units));if slotW<42{slotW=42}
	if !hasData{for i,unit:=range units{slotL:=x+int32(i)*slotW;slotR:=slotL+slotW;if slotR>r.Right{slotR=r.Right};drawText(hdc,unit,RECT{slotL,r.Top,slotR,r.Bottom},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontInvoiceAmountUnit,rgb(28,38,42))};return}
	dollars:=cents/100;if dollars<0{dollars=-dollars};highest:=8;if dollars>0{for i,div:=range divisors{if dollars/div>0{highest=i;break}}}
	for i,unit:=range units{slotL:=x+int32(i)*slotW;slotR:=slotL+slotW;if slotR>r.Right{slotR=r.Right};if i<highest{drawText(hdc,unit,RECT{slotL,r.Top,slotR,r.Bottom},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontInvoiceAmountUnit,rgb(28,38,42));continue};digit:=upperMoneyDigit((dollars/divisors[i])%10);digitSize:=textExtent(hdc,fontInvoiceDigit,digit);unitSize:=textExtent(hdc,fontInvoiceAmountUnit,unit);groupW:=digitSize.Cx+unitSize.Cx+1;groupX:=slotL+(slotR-slotL-groupW)/2;if groupX<slotL{groupX=slotL};drawText(hdc,digit,RECT{groupX,r.Top,groupX+digitSize.Cx+2,r.Bottom},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceDigit,rgb(20,95,190));unitX:=groupX+digitSize.Cx+1;drawText(hdc,unit,RECT{unitX,r.Top,slotR,r.Bottom},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceAmountUnit,rgb(28,38,42))}
	if highest>0{strikeRight:=x+int32(highest)*slotW-3;if strikeRight>x{strikeY:=r.Top+(r.Bottom-r.Top)/2;line(hdc,x+2,strikeY,strikeRight,strikeY,strikePen)}}
}

func drawText(hdc uintptr,text string,r RECT,flags uint32,font uintptr,color uintptr){old,_,_:=procSelectObject.Call(hdc,font);procSetBkMode.Call(hdc,TRANSPARENT);procSetTextColor.Call(hdc,color);p:=utf16Ptr(text);procDrawTextW.Call(hdc,uintptr(unsafe.Pointer(p)),uintptr(len(syscall.StringToUTF16(text))-1),uintptr(unsafe.Pointer(&r)),uintptr(flags));procSelectObject.Call(hdc,old)}
func fillRect(hdc uintptr,r RECT,brush uintptr){procFillRect.Call(hdc,uintptr(unsafe.Pointer(&r)),brush)}
func line(hdc uintptr,x1,y1,x2,y2 int32,pen uintptr){old,_,_:=procSelectObject.Call(hdc,pen);procMoveToEx.Call(hdc,uintptr(x1),uintptr(y1),0);procLineTo.Call(hdc,uintptr(x2),uintptr(y2));procSelectObject.Call(hdc,old)}
func drawRoundBox(hdc uintptr,r RECT,radius int32,fill uintptr,pen uintptr){oldBrush,_,_:=procSelectObject.Call(hdc,fill);oldPen,_,_:=procSelectObject.Call(hdc,pen);procRoundRect.Call(hdc,uintptr(r.Left),uintptr(r.Top),uintptr(r.Right),uintptr(r.Bottom),uintptr(radius),uintptr(radius));procSelectObject.Call(hdc,oldBrush);procSelectObject.Call(hdc,oldPen)}

func paintWindow(hwnd uintptr){
	var ps PAINTSTRUCT;hdc,_,_:=procBeginPaint.Call(hwnd,uintptr(unsafe.Pointer(&ps)));defer procEndPaint.Call(hwnd,uintptr(unsafe.Pointer(&ps)));var rc RECT;procGetClientRect.Call(hwnd,uintptr(unsafe.Pointer(&rc)));fillRect(hdc,rc,mainBrush)
	penSoft,_,_:=procCreatePen.Call(PS_SOLID,1,rgb(210,216,221));penAccent,_,_:=procCreatePen.Call(PS_SOLID,2,rgb(64,139,142));penDark,_,_:=procCreatePen.Call(PS_SOLID,1,rgb(91,105,110));defer procDeleteObject.Call(penSoft);defer procDeleteObject.Call(penAccent);defer procDeleteObject.Call(penDark)
	leftPanel:=RECT{18,18,452,682};drawRoundBox(hdc,leftPanel,18,panelBrush,penSoft);drawText(hdc,"商品輸入",RECT{38,34,250,70},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSection,rgb(38,48,54));drawText(hdc,"固定五筆｜含稅單價輸入完成後自動換算",RECT{38,68,425,96},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(101,112,118))
	header:=RECT{38,101,445,134};fillRect(hdc,header,headerBrush);drawText(hdc,"品名",RECT{45,101,240,134},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(255,255,255));drawText(hdc,"數量",RECT{252,101,324,134},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(255,255,255));drawText(hdc,"含稅單價",RECT{333,101,445,134},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(255,255,255))
	for i:=0;i<5;i++{y:=int32(134+i*52);line(hdc,38,y,445,y,penSoft);drawText(hdc,fmt.Sprintf("%d",i+1),RECT{20,y+6,35,y+40},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(125,132,137))};line(hdc,38,394,445,394,penSoft)
	drawText(hdc,"含稅折扣",RECT{38,421,180,460},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontNormal,rgb(46,55,60));drawText(hdc,"輸入含稅折扣；右側備註顯示未稅折扣",RECT{38,457,425,480},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(116,102,78))
	summaryTop:=int32(532);drawText(hdc,"計算摘要",RECT{38,summaryTop,170,summaryTop+26},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontNormal,rgb(38,48,54));if currentResult.Valid{drawText(hdc,"含稅總計",RECT{38,summaryTop+26,180,summaryTop+50},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(92,100,104));drawText(hdc,formatMoney(currentResult.GrossTotalCents),RECT{185,summaryTop+26,425,summaryTop+50},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontNormal,rgb(35,43,47));drawText(hdc,"營業稅",RECT{38,summaryTop+50,180,summaryTop+74},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(92,100,104));drawText(hdc,formatMoney(currentResult.TaxCents),RECT{185,summaryTop+50,425,summaryTop+74},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontNormal,rgb(35,43,47));drawText(hdc,"未稅銷售額",RECT{38,summaryTop+74,180,summaryTop+98},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(92,100,104));drawText(hdc,formatMoney(currentResult.NetSalesCents),RECT{185,summaryTop+74,425,summaryTop+98},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontNormal,rgb(35,43,47));status:="尚未輸入商品";statusColor:=rgb(115,122,126);if currentResult.HasData{status="✓ 金額核對正確";statusColor=rgb(42,126,86)};drawText(hdc,status,RECT{38,summaryTop+102,425,summaryTop+124},DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS,fontSmall,statusColor);if currentResult.HasData&&currentResult.TailCents!=0{drawText(hdc,"尾差調整："+formatMoney(currentResult.TailCents)+" 元",RECT{38,summaryTop+124,425,summaryTop+146},DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS,fontSmall,rgb(86,108,118))}}else{drawText(hdc,currentResult.ErrorMessage,RECT{38,summaryTop+32,425,summaryTop+136},DT_LEFT|DT_WORDBREAK,fontSmall,rgb(175,55,55))}
	invoice:=RECT{476,18,1198,682};drawRoundBox(hdc,invoice,12,invoiceBrush,penSoft);drawText(hdc,"統一發票（三聯式）",RECT{495,35,1178,82},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontInvoiceTitle,rgb(42,63,69));drawText(hdc,"商品明細與稅額試算",RECT{495,78,1178,103},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontInvoiceSmall,rgb(93,112,117))
	ix1,ix2:=int32(500),int32(1174);tableTop:=int32(112);headerH:=int32(36);rowH:=int32(54);col:=[]int32{ix1,ix1+224,ix1+296,ix1+410,ix1+526,ix2};for _,x:=range col{line(hdc,x,tableTop,x,tableTop+headerH+5*rowH,penAccent)};line(hdc,ix1,tableTop,ix2,tableTop,penAccent);line(hdc,ix1,tableTop+headerH,ix2,tableTop+headerH,penAccent);for i:=1;i<=5;i++{y:=tableTop+headerH+int32(i)*rowH;line(hdc,ix1,y,col[4],y,penAccent)};line(hdc,col[4],tableTop+headerH+5*rowH,ix2,tableTop+headerH+5*rowH,penAccent)
	headers:=[]string{"品名","數量","單價","金額","備註"};for i,h:=range headers{drawText(hdc,h,RECT{col[i]+4,tableTop,col[i+1]-4,tableTop+headerH},DT_CENTER|DT_VCENTER|DT_SINGLELINE,fontInvoiceHeader,rgb(45,86,89))}
	if currentResult.Valid{for i,rr:=range currentResult.Rows{if !rr.Active{continue};y1:=tableTop+headerH+int32(i)*rowH;y2:=y1+rowH;drawText(hdc,rr.DisplayName,RECT{col[0]+8,y1+3,col[1]-8,y2-3},DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS,fontInvoiceText,rgb(35,43,47));drawText(hdc,strconv.FormatInt(rr.Qty,10),RECT{col[1]+4,y1+3,col[2]-6,y2-3},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(35,43,47));drawText(hdc,formatScaledMoney(rr.NetUnitScaled,rr.NetUnitDecimals),RECT{col[2]+4,y1+3,col[3]-6,y2-3},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(35,43,47));drawText(hdc,formatMoney(rr.AdjustedNetCents),RECT{col[3]+4,y1+3,col[4]-6,y2-3},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(35,43,47))};if currentResult.NetDiscountCents!=0{drawText(hdc,"折扣 "+formatMoney(currentResult.NetDiscountCents)+" 元",RECT{col[4]+8,tableTop+headerH+8,col[5]-8,tableTop+headerH+5*rowH-8},DT_LEFT|DT_WORDBREAK,fontInvoiceText,rgb(39,54,59))}}
	summaryY:=tableTop+headerH+5*rowH;labelSplit:=col[3];line(hdc,ix1,summaryY,ix2,summaryY,penAccent);line(hdc,labelSplit,summaryY,labelSplit,summaryY+129,penAccent);for i:=1;i<=3;i++{y:=summaryY+int32(i)*43;line(hdc,ix1,y,ix2,y,penAccent)};vals:=[]string{"0","0","0"};if currentResult.Valid{vals[0]=formatMoney(currentResult.NetSalesCents);vals[1]=formatMoney(currentResult.TaxCents);vals[2]=formatMoney(currentResult.GrossTotalCents)};drawText(hdc,"銷售額合計",RECT{ix1+10,summaryY,labelSplit-8,summaryY+43},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceHeader,rgb(45,86,89));drawText(hdc,vals[0],RECT{labelSplit+8,summaryY,ix2-12,summaryY+43},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(28,38,42));taxY:=summaryY+43;drawText(hdc,"營業稅",RECT{ix1+10,taxY,ix1+92,taxY+43},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceHeader,rgb(45,86,89));drawText(hdc,"☑ 應稅　□ 零稅率　□ 免稅",RECT{ix1+92,taxY,labelSplit-8,taxY+43},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceSmall,rgb(45,70,74));drawText(hdc,vals[1],RECT{labelSplit+8,taxY,ix2-12,taxY+43},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(28,38,42));totalY:=summaryY+86;drawText(hdc,"總計",RECT{ix1+10,totalY,labelSplit-8,totalY+43},DT_LEFT|DT_VCENTER|DT_SINGLELINE,fontInvoiceHeader,rgb(45,86,89));drawText(hdc,vals[2],RECT{labelSplit+8,totalY,ix2-12,totalY+43},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontInvoiceText,rgb(28,38,42));chineseY:=summaryY+129;chineseH:=int32(82);line(hdc,ix1,chineseY+chineseH,ix2,chineseY+chineseH,penAccent);drawFixedChineseTotal(hdc,"總計新臺幣",currentResult.GrossTotalCents,currentResult.Valid&&currentResult.HasData,RECT{ix1+10,chineseY,ix2-10,chineseY+chineseH},penDark)
	drawText(hdc,"© 2026 C.C.LIU All Rights Reserved.",RECT{830,646,1182,676},DT_RIGHT|DT_VCENTER|DT_SINGLELINE,fontSmall,rgb(132,140,145))
}

func showMessage(title,message string,flags uintptr){procMessageBoxW.Call(mainHwnd,uintptr(unsafe.Pointer(utf16Ptr(message))),uintptr(unsafe.Pointer(utf16Ptr(title))),flags)}
