<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>CYEnvelope</AssemblyName>
    <ApplicationIcon>../../assets/ENV.ico</ApplicationIcon>
    <ApplicationManifest>../../assets/app.manifest</ApplicationManifest>
    <PublishAot>true</PublishAot>
  </PropertyGroup>
</Project>
