import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const read = relative => fs.readFileSync(path.join(ROOT, relative), 'utf8');

const css = read('public/adaptive-ui.css');
const js = read('public/adaptive-ui.js');
const loginHtml = read('public/login.html');

assert.match(css, /@media \(max-width: 767px\)/);
assert.match(css, /@media \(min-width: 768px\) and \(max-width: 1023px\)/);
assert.match(css, /@media \(min-width: 1024px\)/);
assert.match(css, /@media \(min-width: 1360px\)/);
assert.match(css, /\.v21-mobile-main-nav\.v21-mobile-bottom-nav\s*\{[\s\S]*?position:\s*fixed !important;[\s\S]*?bottom:\s*0;/);
assert.match(css, /\.ledger-month-tools\.v0215-toolbar-ready/);
assert.match(css, /\.mobile-utility-dialog\s*\{[\s\S]*?width:\s*min\(350px, calc\(100vw - 28px\)\) !important/);
assert.match(css, /\.mobile-settings-dialog \.settings-nav\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-dialog-heading\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.quick-chip-list[\s\S]*?overflow-x:\s*auto !important/);
assert.match(css, /body\.v21-mobile-app \.entry-card\s*\{[\s\S]*?min-height:\s*calc\(100dvh - 110px - env\(safe-area-inset-bottom\)\) !important/);
assert.match(css, /\.ledger-card\.is-loading \.table-wrap::after[\s\S]*?content:\s*"載入中…"/);
assert.match(css, /\.mobile-opening-dialog #openingRows\s*\{[\s\S]*?flex:\s*0 1 auto !important/);

assert.match(css, /:root\s*\{\s*background:\s*#fff;/);
assert.match(css, /\.v21-mobile-main-nav\.v21-mobile-bottom-nav\s*\{[\s\S]*?box-shadow:\s*none !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-row\s*\{[\s\S]*?justify-content:\s*center !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-row > span[\s\S]*?font-size:\s*15px !important/);
assert.match(css, /html\.mobile-entry-income-canvas[\s\S]*?background:\s*#f4fbf6 !important/);
assert.match(css, /html\.mobile-entry-expense-canvas[\s\S]*?background:\s*#fff6f5 !important/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog\[data-mobile-utility="lock"\] \.mobile-lock-native-field[\s\S]*?display:\s*none !important/);
assert.match(css, /#mobileLockMonthControls \.mobile-lock-month-selects[\s\S]*?grid-template-columns:/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog\[data-mobile-utility="categories"\] #categoryManager[\s\S]*?overflow-y:\s*auto !important/);
assert.match(css, /\.mobile-category-footer[\s\S]*?grid-template-columns:/);
assert.doesNotMatch(loginHtml, /class="subtitle"/);
assert.doesNotMatch(loginHtml, /class="identity-note"/);
assert.doesNotMatch(loginHtml, /class="password-note"/);
assert.doesNotMatch(loginHtml, />CYAccounting Web<\/p>/);

assert.match(js, /trigger\.id = 'mobileAccountMenuButton'/);
assert.match(js, /data-mobile-account-action="logout">登出/);
assert.doesNotMatch(js, /data-mobile-account-action="settings"/);
assert.match(js, /button\.id = 'mobileLedgerMoreButton'/);
assert.match(js, /data-mobile-ledger-action="accounts">帳戶設定/);
assert.match(js, /data-mobile-ledger-action="categories">科目設定/);
assert.match(js, /data-mobile-ledger-action="lock">月份鎖帳/);
assert.match(js, /data-mobile-ledger-action="export">匯出 Excel/);
assert.doesNotMatch(js, /data-mobile-ledger-action="opening">期初餘額/);
assert.match(js, /mobileLedgerBalanceButton/);
assert.match(js, /window\.cyOpenMobileUtility = openMobileUtility/);
assert.match(js, /window\.cyOpenMobileLedgerOpening = \(\) => openMobileUtility\('opening'\)/);
assert.match(js, /window\.cyOpenMobileLedgerLock = \(\) => openMobileUtility\('lock'\)/);
assert.match(js, /window\.cyOpenMobileSettingsPane = tab => openMobileUtility\(tab\)/);
assert.doesNotMatch(js, /openingDialog\.showModal\(\)/);
assert.doesNotMatch(js, /mobileLedgerLockDialogV0215/);

console.log('Adaptive UI regression checks passed.');

assert.match(js, /function renderMobileAccountManager\(\)/);
assert.match(js, /function renderSettingsCategoryManager\(\)/);
assert.match(js, /if \(!window\.matchMedia\(SETTINGS_MANAGER_DESKTOP\)\.matches\) return renderMobileAccountManager\(\)/);
assert.doesNotMatch(js, /function renderMobileCategoryManager\(\)/);
assert.match(js, /dialog\.classList\.add\('mobile-utility-dialog', 'mobile-settings-dialog'\)/);
assert.match(js, /dialog\.classList\.add\('mobile-opening-dialog'\)/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog/);
assert.match(css, /#settingsDialog\.mobile-opening-dialog/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog,\s*#settingsDialog\.mobile-utility-dialog\[open\][\s\S]*?height:\s*fit-content !important/);
assert.match(js, /function bindMobileAccountReorder\(host\)/);
assert.match(js, /addEventListener\('pointerdown'/);
assert.match(js, /addEventListener\('pointermove'/);
assert.match(js, /applySettingsAccountOrder/);
assert.match(js, /\/api\/accounts\/reorder/);
assert.match(js, /state\.accounts = nextIds\.map/);
assert.match(js, /function setupMobileCanvasContinuation\(\)/);
assert.match(js, /window\.cySyncMobileCanvasContinuation = syncMobileCanvasContinuation/);
assert.match(js, /function setupMobileLockMonthControls\(dialog\)/);
assert.match(js, /id="mobileLockYear"/);
assert.match(js, /id="mobileLockMonth"/);
assert.match(js, /function ensureMobileCategoryActions\(pane, hasPersistedGroup\)/);
assert.match(js, /data-mobile-category-add/);
assert.match(js, /data-mobile-group-add/);
assert.match(js, /function optimisticAddSettingsGroup\(rawName\)/);
assert.match(js, /function optimisticAddSettingsCategory\(rawName, groupId\)/);
assert.match(js, /class="settings-category-tree"/);
assert.match(js, /class="settings-category-branch/);
assert.match(js, /class="settings-category-leaf/);
assert.match(js, /data-account-archive=/);
assert.match(js, /data-account-restore=/);
assert.match(js, /data-account-permanent-delete=/);
assert.match(js, /state\.groups = \[\.\.\.\(state\.groups \|\| \[\]\), \{ id: tempId/);
assert.match(js, /state\.categories = \[\.\.\.\(state\.categories \|\| \[\]\), \{/);
assert.match(js, /filter\(group => group\.kind === kind && Number\(group\.id\) > 0\)/);

assert.match(js, /window\.cySettingsManager = \{/);
assert.match(js, /function renderSettingsAccountManager\(\)/);
assert.match(js, /function renderSettingsCategoryManager\(\)/);
assert.match(js, /function ensureSettingsManagerDialog\(\)/);
assert.match(css, /\.settings-dialog-field\[hidden\]\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.settings-manager-dialog-actions button\s*\{[\s\S]*?align-items:\s*center/);
assert.match(css, /\.settings-category-tree\s*\{[\s\S]*?border-top:/);
assert.match(css, /\.settings-category-leaf\s*\{[\s\S]*?grid-template-columns:/);
assert.doesNotMatch(css, /\.mobile-category-group\s*\{|\.mobile-category-row\s*\{/);
assert.match(css, /mobile-lock-native-field\s*\{[\s\S]*?display:\s*none !important/);
assert.doesNotMatch(js, /renderV21Build1[456](?:Account|Category)Manager|renderV0211(?:Account|Category)Manager|renderV0212CategoryManager|openV0212/);
assert.doesNotMatch(css, /v0211-(?:account|category|default|group)|v0212-(?:manager|dialog|category|group|favorite|edit|toolbar|kind|legacy|empty|add)/);
