import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, '..');
const read = relative => fs.readFileSync(path.join(ROOT, relative), 'utf8');

const css = read('public/adaptive-ui.css');
const js = read('public/adaptive-ui.js');
const ledger = read('public/ledger-tools.js');
const backupUi = read('public/backup-ui.js');
const loginHtml = read('public/login.html');
const indexHtml = read('public/index.html');

assert.match(css, /@media \(max-width: 767px\)/);
assert.match(css, /html\[data-tablet-layout\]/);
assert.match(css, /@media \(min-width: 1024px\)/);
assert.match(css, /@media \(min-width: 1360px\)/);
assert.match(css, /\.cy-mobile-main-nav\.cy-mobile-bottom-nav\s*\{[\s\S]*?position:\s*fixed !important;[\s\S]*?bottom:\s*0;/);
assert.doesNotMatch(css, /cy-toolbar-ready|ledger-desktop-tools|ledger-period-tools|mobileLedger(?:MoreButton|BalanceButton|ToolsSheet|ToolsBackdrop|MonthDisplay)/);
assert.match(css, /\.ledger-month-tools\s*\{/);
assert.match(css, /\.mobile-utility-dialog\s*\{[\s\S]*?width:\s*min\(350px, calc\(100vw - 28px\)\) !important/);
assert.match(css, /\.mobile-settings-dialog \.settings-nav\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-dialog-heading\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.quick-chip-list[\s\S]*?overflow-x:\s*auto !important/);
assert.match(css, /body\.cy-mobile-app \.entry-card\s*\{[\s\S]*?min-height:\s*calc\(100dvh - 110px - env\(safe-area-inset-bottom\)\) !important/);
assert.match(css, /\.ledger-card\.is-loading \.table-wrap::after[\s\S]*?content:\s*"載入中…"/);
assert.match(css, /\.mobile-opening-dialog #openingRows\s*\{[\s\S]*?flex:\s*0 1 auto !important/);

assert.match(css, /:root\s*\{\s*background:\s*#fff;/);
assert.match(css, /\.cy-mobile-main-nav\.cy-mobile-bottom-nav\s*\{[\s\S]*?box-shadow:\s*none !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-row\s*\{[\s\S]*?justify-content:\s*center !important/);
assert.match(css, /\.mobile-opening-dialog \.opening-row > span[\s\S]*?font-size:\s*15px !important/);
assert.match(css, /html\.mobile-entry-income-canvas[\s\S]*?background:\s*#f4fbf6 !important/);
assert.match(css, /html\.mobile-entry-expense-canvas[\s\S]*?background:\s*#fff6f5 !important/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog\[data-mobile-utility="lock"\] \.mobile-lock-native-field[\s\S]*?display:\s*none !important/);
assert.match(css, /#mobileLockMonthControls \.mobile-lock-month-selects[\s\S]*?grid-template-columns:/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog\[data-mobile-utility="categories"\] #categoryManager[\s\S]*?overflow-y:\s*auto !important/);
assert.match(css, /\.mobile-category-footer[\s\S]*?grid-template-columns:/);
assert.doesNotMatch(loginHtml, /class="subtitle"/);
assert.doesNotMatch(loginHtml, /class="identity-note"/);
assert.doesNotMatch(loginHtml, /class="password-note"/);
assert.doesNotMatch(loginHtml, />CYAccounting Web<\/p>/);

assert.match(js, /trigger\.id = 'mobileAccountMenuButton'/);
assert.match(js, /data-mobile-account-action="tablet-preview" hidden>測試用平板版/);
assert.match(js, /data-mobile-account-action="logout">登出/);
assert.match(js, /previewButton\.textContent = preview \? '返回手機版' : '測試用平板版'/);
assert.match(js, /sessionStorage\.setItem\(key, '1'\)/);
assert.match(js, /function isTabletPreviewMode\(\)/);
assert.doesNotMatch(js, /data-mobile-account-action="settings"/);
assert.match(ledger, /id="ledgerMoreButton"/);
assert.match(ledger, /data-mobile-ledger-action="accounts">帳戶設定/);
assert.match(ledger, /data-mobile-ledger-action="categories">科目設定/);
assert.match(ledger, /data-mobile-ledger-action="lock">月份鎖帳/);
assert.match(ledger, /data-mobile-ledger-action="backup" hidden>備份資訊/);
assert.match(ledger, /data-mobile-ledger-action="export">匯出 Excel/);
assert.match(backupUi, /user\?\.role !== 'SUPER_ADMIN'/);
assert.match(backupUi, /window\.cyOpenMobileBackupInfo = openMobileBackupInfo/);
assert.match(css, /tbody > tr:not\(\.account-group-row\):not\(\.ledger-message-row\)/);
assert.match(css, /\.ledger-card tbody > tr\.ledger-message-row > td\.empty[\s\S]*?border:\s*0 !important;[\s\S]*?text-align:\s*center !important/);
assert.match(css, /tr\.ledger-row:not\(\.inline-editing\) > td:nth-child\(4\)[\s\S]*?padding-left:\s*5px !important/);
assert.match(css, /@media \(max-width: 767px\)[\s\S]*?#mobileEntrySecondaryButton[\s\S]*?display:\s*block !important/);
assert.match(css, /\.entry-grid #txDate[\s\S]*?appearance:\s*auto !important;[\s\S]*?-webkit-text-fill-color:\s*#243345 !important/);
assert.match(css, /grid-template-areas:[\s\S]*?"amount"[\s\S]*?"\."[\s\S]*?"message"[\s\S]*?"save"[\s\S]*?"secondary"[\s\S]*?grid-template-rows:\s*repeat\(8, max-content\) auto repeat\(3, max-content\) !important/);
assert.match(css, /\.entry-grid > label,[\s\S]*?\.quick-tool-row\s*\{[\s\S]*?min-height:\s*46px !important;[\s\S]*?height:\s*46px !important/);
assert.match(css, /\.entry-card label > span,[\s\S]*?\.quick-tool-label\s*\{[\s\S]*?font-size:\s*13\.5px !important/);
assert.match(css, /\.entry-grid input,[\s\S]*?\.entry-grid select\s*\{[\s\S]*?height:\s*36px !important;[\s\S]*?font-size:\s*17px !important/);
assert.doesNotMatch(css, /\.tablet-entry-controls,\s*#mobileEntrySecondaryButton\s*\{\s*display:\s*none !important;/);
assert.match(js, /function setupTouchWorkspaceEntrySecondaryAction\(\)/);
assert.match(js, /button\.textContent = cyTouchWorkspaceEdit \? '取消' : '清空'/);
assert.match(css, /\.entry-grid > #saveButton\s*\{[\s\S]*?grid-area:\s*save !important;[\s\S]*?width:\s*100% !important/);
assert.doesNotMatch(css, /\.entry-grid > #saveButton\s*\{\s*grid-area:\s*save !important;[\s\S]{0,220}?grid-row:\s*auto !important/);
assert.match(js, /trigger\.hidden = true;[\s\S]*?cy-mobile-account-name\"><\/span>/);
assert.match(js, /window\.addEventListener\('cyacc:session-ready', syncMobileWorkspaceMobileIdentity\)/);
assert.match(js, /const ready = Boolean\(main\) && !source\.classList\.contains\('hidden'\)/);
assert.match(js, /if \(!touchIdentity \|\| !ready\)[\s\S]*?trigger\.hidden = true;[\s\S]*?return;/);
assert.match(js, /triggerName\.textContent = main;[\s\S]*?trigger\.hidden = false;/);
assert.doesNotMatch(js, /new MutationObserver\(syncMobileWorkspaceMobileIdentity\)/);
assert.doesNotMatch(js, /cy-mobile-account-name\">帳號|mobileAccountMenuName\">帳號/);
assert.match(js, /cancelTouchWorkspaceMobileEditAndReturn\(\)/);
assert.doesNotMatch(js, /setupMobileEntryDateDisplay|cySyncMobileEntryDateDisplay|cy-mobile-entry-date-display/);
assert.doesNotMatch(css, /cy-mobile-entry-date-display/);
assert.doesNotMatch(ledger, /data-mobile-ledger-action="opening">期初餘額/);
assert.match(ledger, /id="ledgerBalanceButton"/);
assert.match(ledger, /function setupLedgerToolbar\(\)/);
assert.match(js, /function startAdaptiveUi\(\)/);
assert.match(indexHtml, /cyacc-tablet-preview/);
assert.match(indexHtml, /landscape \? '1194' : '820'/);
assert.match(indexHtml, /data\.tabletPreview|dataset\.tabletPreview/);
assert.doesNotMatch(js, /\b[A-Za-z_$][A-Za-z0-9_$]*(?:V|v)\d{2,4}[A-Za-z0-9_$]*\b/);
assert.doesNotMatch(css, /[-_](?:V|v)\d{2,4}(?:[-_A-Za-z0-9]|$)/);
assert.doesNotMatch(js, /setupMobileWorkspaceLedgerTools|setupTouchWorkspaceToolbar|setupTouchWorkspaceMonthDisplay|moveImportButton/);
assert.match(js, /window\.cyOpenMobileUtility = openMobileUtility/);
assert.match(js, /window\.cyOpenMobileLedgerOpening = \(\) => openMobileUtility\('opening'\)/);
assert.match(js, /window\.cyOpenMobileLedgerLock = \(\) => openMobileUtility\('lock'\)/);
assert.match(js, /window\.cyOpenMobileSettingsPane = tab => openMobileUtility\(tab\)/);
assert.doesNotMatch(js, /openingDialog\.showModal\(\)/);

console.log('Adaptive UI regression checks passed.');

assert.match(js, /function renderMobileAccountManager\(\)/);
assert.match(js, /function renderSettingsCategoryManager\(\)/);
assert.match(js, /if \(!isDesktopInteractionWorkspace\(\)\) return renderMobileAccountManager\(\)/);
assert.doesNotMatch(js, /function renderMobileCategoryManager\(\)/);
assert.match(js, /dialog\.classList\.add\('mobile-utility-dialog', 'mobile-settings-dialog'\)/);
assert.match(js, /dialog\.classList\.add\('mobile-opening-dialog'\)/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog/);
assert.match(css, /#settingsDialog\.mobile-opening-dialog/);
assert.match(css, /#settingsDialog\.mobile-utility-dialog,\s*#settingsDialog\.mobile-utility-dialog\[open\][\s\S]*?height:\s*fit-content !important/);
assert.match(js, /function bindMobileAccountReorder\(host\)/);
assert.match(js, /addEventListener\('pointerdown'/);
assert.match(js, /addEventListener\('pointermove'/);
assert.match(js, /applySettingsAccountOrder/);
assert.match(js, /\/api\/accounts\/reorder/);
assert.match(js, /state\.accounts = nextIds\.map/);
assert.match(js, /function setupMobileCanvasContinuation\(\)/);
assert.match(js, /window\.cySyncMobileCanvasContinuation = syncMobileCanvasContinuation/);
assert.match(js, /function setupMobileLockMonthControls\(dialog\)/);
assert.match(js, /id="mobileLockYear"/);
assert.match(js, /id="mobileLockMonth"/);
assert.match(js, /function ensureMobileCategoryActions\(pane, hasPersistedGroup\)/);
assert.match(js, /data-mobile-category-add/);
assert.match(js, /data-mobile-group-add/);
assert.match(js, /function optimisticAddSettingsGroup\(rawName\)/);
assert.match(js, /function optimisticAddSettingsCategory\(rawName, groupId\)/);
assert.match(js, /class="settings-category-tree"/);
assert.match(js, /class="settings-category-branch/);
assert.match(js, /class="settings-category-leaf/);
assert.match(js, /data-account-archive=/);
assert.match(js, /data-account-restore=/);
assert.match(js, /data-account-permanent-delete=/);
assert.match(js, /state\.groups = \[\.\.\.\(state\.groups \|\| \[\]\), \{ id: tempId/);
assert.match(js, /state\.categories = \[\.\.\.\(state\.categories \|\| \[\]\), \{/);
assert.match(js, /filter\(group => group\.kind === kind && Number\(group\.id\) > 0\)/);

assert.match(js, /window\.cySettingsManager = \{/);
assert.match(js, /function renderSettingsAccountManager\(\)/);
assert.match(js, /function renderSettingsCategoryManager\(\)/);
assert.match(js, /function ensureSettingsManagerDialog\(\)/);
assert.match(css, /\.settings-dialog-field\[hidden\]\s*\{[\s\S]*?display:\s*none !important/);
assert.match(css, /\.settings-manager-dialog-actions button\s*\{[\s\S]*?align-items:\s*center/);
assert.match(css, /\.settings-category-tree\s*\{[\s\S]*?border-top:/);
assert.match(css, /\.settings-category-leaf\s*\{[\s\S]*?grid-template-columns:/);
assert.doesNotMatch(css, /\.mobile-category-group\s*\{|\.mobile-category-row\s*\{/);
assert.match(css, /mobile-lock-native-field\s*\{[\s\S]*?display:\s*none !important/);
